### ISSUE TITLE
Integration with cpanel api 2

### ISSUE THREAD

**Issue by nickwilliams999** [DamageESP/whmcs-js#2]
Hi,

Do you think it would be possible to provide something that would integrate with cPanels API2?

Something like the great work you have done on whmcs-js?

I am attempting to create some folders on signup for my users within their cpanel.. This is what I am looking to use.

https://documentation.cpanel.net/display/DD/cPanel+API+2+Functions+-+Fileman%3A%3Amkdir

Any chance of you doing something like this ?

**Comment by DamageESP** [comment]
Hi @nickwilliams999, 

Yes, of course it would be possible. In fact, it would be a very similar implementation:

- Identify in the destination cPanel installation using API credentials.
- Make calls to the API using that instance.

Unfortunately, I don't have the time to do something like that right now.

You can try this library: https://github.com/vially/cpanel-lib Although it's kinda old and I don't know if it still works. You can maybe adapt it to ES6 and to the new API if there's a new one.

Good idea, by the way. 😄
