### ISSUE TITLE
Expanding Products module

### ISSUE THREAD

**Issue by HarunKilic** [DamageESP/whmcs-js#3]
Hi

Great job with whmcs-js :)

**Comment by DamageESP** [comment]
Hey @Fl4zher, thank you very much!

If there are features missing, don't hesitate to tell me and I will push them! 😉

**Comment by HarunKilic** [comment]
Actually there is. Getting products :D

**Comment by HarunKilic** [comment]
I've made one to test with, which do work :) 

```
const WHMCS = require('./whmcs');

class Test extends WHMCS {
  constructor(config) {
    super(config);
  }

  getProducts(opts) {
    const options = {
      action: 'GetProducts',
      ...opts
    };

    return this.callApi(options);
  }
}

module.exports = Test;
```

**Comment by DamageESP** [comment]
Wow, you're actually right. I don't know how I missed that one.

I'll be pushing an update in a minute. Sorry.

**Comment by HarunKilic** [comment]
Thanks :D
