### ISSUE TITLE
getProducts in wrong module

### ISSUE THREAD

**Issue by HarunKilic** [DamageESP/whmcs-js#4]
getProducts are listed here: 	https://github.com/DamageESP/whmcs-js/blob/1b15254f65bbd012ea30c2ff4cf4b4cc28171bc5/modules/Orders.js#L40

Shouldn't it be listed in Products module?

**Comment by DamageESP** [comment]
Hi @Fl4zher, [according to WHMCS' own classification](https://developers.whmcs.com/api/api-index/), it should be under the Orders module.

Their reasoning behind this classification seems to be:

> Retrieve configured products matching provided criteria
> 
> NOTE: This API method is designed to be used in the building of custom order forms. As a result, only custom fields that have the ‘Show on Order Form’ setting enabled will be returned for a given product.

**Comment by HarunKilic** [comment]
Yes i see :)
