### ISSUE TITLE
Inserting data into customfields (client level)

### ISSUE THREAD

**Issue by nickwilliams999** [DamageESP/whmcs-js#5]
Hi,

Do you know how the customfields works in addClient? 

I have done the following but it is not placing the data anywhere... 

` var custommoduledata = JSON.stringify(req.body.selected);
`
Inside addClient

`      customfields: custommoduledata .toString('base64'),
`

**Comment by DamageESP** [comment]
Hello,

From what I can see, you are not encoding the `customfields` into base64.
You can do this using `btoa`.

```javascript
const custommoduledata = JSON.stringify(req.body.selected)

// Inside addClient:
addClient({
  otherProperties,
  customfields: btoa(custommoduledata),
})
```

Hope this works.

Thanks for using this library. I will probably update it soon to include latest changes in WHMCS 7.8 (if there are any changes).

**Comment by nickwilliams999** [comment]
Hi,

Thanks for your help, and your library is really helping!

Although this does not seem to be actually sending the data, is there a way of specifying that it should be placed in the custom field that I created?

![Capture](https://user-images.githubusercontent.com/7601014/65719021-c409b000-e09c-11e9-870b-1c8b9ef5148d.PNG)

**Comment by nickwilliams999** [comment]
Any ideas?#

I am now trying this but still no luck..

```
var testcustomfield = new Array("Saab", "Volvo", "BMW");
  const testcustomfieldserial = JSON.stringify(testcustomfield);

addClient
    .addClient({

      customfields: btoa(testcustomfieldserial),

    })
```

**Comment by DamageESP** [comment]
Hi.

I would guess the array format is incorrect. I think it should be an associative array, maybe something like this:

```javascript
const testcustomfield = {
  customField: 'myCustomValue',
  myOtherCustomField: 'myAwesomeValue'
}
const testcustomfieldserial = JSON.stringify(testcustomfield)

.addClient({
  customfields: btoa(testcustomfieldserial),
})
```

But I didn't test this. Otherwise please refer to WHMCS support team to get help with this.

**Comment by nickwilliams999** [comment]
Hi,

Thanks, that didn't work and there is only resources on how to add this in PHP.

If you have any other ideas then let me know, I will keep trying to figure it out.

**Comment by nickwilliams999** [comment]
Hi,

I just wanted to post that I have figured out the answer to this for anyone who has this issue in the future...

I think what this came down to is that JSON.stringify and btoa was sending something different than what WHMCS was expecting. With this in ming i replaced these functions with:

http://locutus.io/php/url/base64_encode/ and http://locutus.io/php/var/serialize/ 

```
const module = {
// 47 is the ID in tblcustomfields for the customfield
// data[0] is the data passed to the page
    47: data[0]
  }

  // Serialize
  const moduleserial = serialize(module);

addClient
    .addClient({
      customfields: base64_encode(moduleserial)
    })
```
Enjoy 🙂
Regards,

Nick Williams
